name: ZEIT Now Deployment
on: [push]
jobs:
  deploy:
     runs-on: [ubuntu-latest]
     steps:
       - uses: actions/checkout@v2
       - uses: amondnet/now-deployment@v2.0.1
         with:
           zeit-token: ${{secrets.ZEIT_TOKEN}}
           zeit-team-id: ceskodigital
           now-project-id: location-histor-fe
           now-org-id: ceskodigital
