name: ZEIT Now Deployment
on:
  push:
    branches: 
      - master
jobs:
  deploy:
     runs-on: [ubuntu-latest]
     steps:
       - uses: actions/checkout@v2
       - uses: amondnet/now-deployment@v2.0.1
         with:
           zeit-token: ${{ secrets.ZEIT_TOKEN }}
           zeit-team-id: ceskodigital
           now-args: '--prod'
           now-project-id: ${{ secrets.NOW_PROJECT_ID }}
           now-org-id: ${{ secrets.NOW_ORG_ID }}
